runtime: nodejs10
env: standard
service: apartment-finder

instance_class: B2

env_variables:
  MIGRATIONS_RUN: true
  POSTGRES_HOST: 35.234.83.230
  POSTGRES_PORT: 5432
  POSTGRES_DB_NAME: apartment-finder
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: 181199142vorbarra

handlers:
  - url: /.*
    script: auto

manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10
