version: "3.4"

# Used for persisting data between startups
volumes:
  apartment-finder-postgres-volume:
services:
  postgres: &postgres
    image: postgres
    restart: on-failure
    ports:
      - "5439:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: apartment-finder
    volumes:
      - apartment-finder-postgres-volume:/var/lib/postgresql/data
